server:
  port: 8080

app:
  azure-search:
    endpoint: https://naki-search.search.windows.net
    api-key: ${AZURE_SEARCH_API_KEY}
    index: bank-policies
    text-field: content
    k: 5
    mode: text                # o 'semantic'
    semantic-config: bank-semantic-config # nombre de la semantic configuration del Ã­ndice

management:
  tracing:
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces